language: python
python: 3.5
sudo: false
env:
    - TOX_ENV=py27-django18
    - TOX_ENV=py34-django18
    - TOX_ENV=py33-django18
    - TOX_ENV=py27-django110
    - TOX_ENV=py34-django110
    - TOX_ENV=py35-django110
    - TOX_ENV=py36-django110
    - TOX_ENV=py27-django111
    - TOX_ENV=py34-django111
    - TOX_ENV=py35-django111
    - TOX_ENV=py36-django111
install:
    - pip install --upgrade pip
    - pip install tox coveralls
script:
    - tox -e $TOX_ENV
after_success: coveralls
